### ISSUE TITLE
Missing from stage0 list

### ISSUE THREAD

**Issue by jethrolarson** [rbuckton/proposal-partial-application#17]
Shouldn't this proposal be linked on https://github.com/tc39/proposals/blob/master/stage-0-proposals.md ?

**Comment by jethrolarson** [comment]
Oh wait, I see it on Stage 1 now. I guess the readme should be updated to stage 1 then.

**Comment by rbuckton** [comment]
Fixed by 143d180ee98d23ad8a1b31ce39801921259647f2
