### ISSUE TITLE
Partial Application in the middle

### ISSUE THREAD

**Issue by Jamesernator** [rbuckton/proposal-partial-application#3]
The examples only show left and right so it's not clear to me if `f(1, ?, 2)` would be supported, I personally would find it very surprising if `f(1, ?, 2)` wasn't equivalent to `_ => f(1, _, 2)`, `setTimeout` particularly comes to mind for this, but I'm sure there's others.

**Comment by rbuckton** [comment]
This is definitely supported. I'll add an example.

**Comment by rbuckton** [comment]
Fixed by 8cbd1c0f6c9e6e115211913de8cfd5464a6cf54b.
